version: '3'

services:
  masternode:
    build:
      context: .
      dockerfile: dockerfile.local
    ports:
      - 8080:80
    environment:
      - MN=TRUE
  node:
    build:
      context: .
      dockerfile: dockerfile.local